build:
  commands:
    - cd ../frontend && npm ci && npm run build

command:
  - uvicorn
  - main:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  - name: GMAIL_SENDER
    valueFrom: GMAIL_SENDER
  - name: GMAIL_APP_PASS
    valueFrom: GMAIL_APP_PASS
