command:
  - uvicorn
  - main:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  - name: GMAIL_SENDER
    valueFrom: gmail-sender
  - name: GMAIL_APP_PASS
    valueFrom: gmail-pass
  - name: SQL_WAREHOUSE_ID
    valueFrom: sql-wh-id
  - name: GENIE_SPACE_ID
    valueFrom: genie-id
  - name: DATABRICKS_TOKEN
    valueFrom: db-token
